#+title: Graphing Sine and Cosine
#+author: Chase Mathison
#+date: 14 February 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil 
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}
#+latex_header: \newcommand{\R}{\mathbb{R}}
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{pgfplots}

* Announcements
** Announcements
1. Homework and Project in MyOpenMath.
2. Office hours, 10am - 11am.

* Lecture
** Graphing \(\sin(\theta)\) and \(\cos(\theta)\)

#+begin_export latex
\begin{tikzpicture}[scale=2]
  \draw[help lines, step = 0.25] (-1.3,-1.3) grid (1.3,1.3);
  \draw[->] (-1.3,0) -- (1.3,0) node[right] {$x$};
  \draw[->] (0,-1.3) -- (0,1.3) node[above] {$y$};
  \foreach \x in {-1,-0.5,0.5,1} {\draw (\x,1pt) -- (\x,-1pt) node[below] {$\x$};}
  \foreach \y in {-1,-0.5,0.5,1} {\draw (1pt,\y) -- (-1pt,\y) node[left] {$\y$};}
  \node [below left] at (0,0) {$0$};
  \draw (0,0) circle [radius = 1];
\end{tikzpicture}
#+end_export

** Graphing \(\sin(\theta)\) and \(\cos(\theta)\)
#+begin_export latex
\begin{tikzpicture}
  \begin{scope}[scale=1.75]
  \draw[help lines, xstep = 0.3927, ystep = 0.5] (-3.2,-1.1) grid (3.2,1.1);
  \draw[->] (-3.2,0) -- (3.2,0) node[right] {$\theta$};
  \draw[->] (0,-1.1) -- (0,1.1) node[above] {$y$};
  \foreach \x/\xtext in {-3.14/{-2\pi},-1.57/-\pi,1.57/\pi,3.14/{2\pi}} {\draw (\x,1pt) -- (\x,-1pt) node[below] {$\xtext$};}
  \foreach \y in {-1,-0.5,0.5,1} {\draw (1pt,\y) -- (-1pt,\y) node[left] {$\y$};}
  \node [below left] at (0,0) {$0$};
  \end{scope}
\end{tikzpicture}
#+end_export

** The Period of \(\sin(\theta)\) and \(\cos(\theta)\)
We've already discussed the period of \(\sin(\theta)\) and
\(\cos(\theta)\), but let's see if we can determine these from the
graphs we just drew.

** Special Characteristics of Sine and Cosine functions

The following are special characteristics we can determine from the graphs of \(\sin(\theta)\) and \(\cos(\theta)\):

1. The domain of both functions is: _\hspace*{1in}_.
2. The range of both functions is: _\hspace*{1in}_.
3. Both functions are periodic with period: _\hspace*{1in}_.
4. \(\sin(\theta)\) is _\hspace*{1in}_, in other words, the graph of \(y = \sin(\theta)\) is symmetric about the origin.
5. \(\cos(\theta)\) is _\hspace*{1in}_, in other words, the graph of \(y = \cos(\theta)\) is symmetric about the y-axis.

** Investigating General Sinusoidal Functions

In general, we call any periodic function that oscillates between a
maximum value and a minimum value _\hspace*{1in}_.  Sinusoidal
functions in general can be written as:

\[y = \hspace{1in}\]
or
\[y = \hspace{1in}\]

Let's investigate how all of these numbers affect the shape of the
graph of \(\sin\) and \(\cos\).

** \(A\) (With C and D both 0)

** Amplitude

** \(B\) (With C and D both 0)

** Period

** \(C\)

** The Phase Shift

** \(D\)

** The Midline

** Putting it all together
So to graph a sinusoidal function \(y = A\sin\left(Bx - C \right) + D\) or \(y = A\cos \left( Bx - C \right) + D\):

***                                                               :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
1. Determine the Amplitude: \( \left| A \right|\)
2. Determine the Period: \( \frac{2\pi}{|B|}\)
3. Determine the Phase Shift: \(\frac{C}{B}\)
4. Determine the midline: \(y = D\)

** A Modeling Problem
Model the number of hours of daylight in Winchester, VA \(t\) days
after January 1 using a sinusoidal function.

\vspace{10in}

